### ISSUE TITLE
References for linear regression?

### ISSUE THREAD

**Issue by Otamio** [UC-MACSS/persp-model_W18#106]
I found the discussion of linear regression on Monday to be a bit math heavy. Are there any references we can look into?

**Comment by sushmitavgopalan16** [comment]
I think Chapter 3 of *An Introduction to Statistical Learning' https://link-springer-com.proxy.uchicago.edu/book/10.1007%2F978-1-4614-7138-7 is a good starting point!

**Comment by Otamio** [comment]
Yes, I did see that. That is a good reference for conducting linear models, but I think we covered some linear algebra topics on Monday. Do you have any recommendations?

**Comment by cernhofer** [comment]
This article is a decent description of how linear regression can be interpreted with linear algebra:

https://medium.com/@andrew.chamberlain/the-linear-algebra-view-of-least-squares-regression-f67044b7f39b

All MACSS students are required to fulfill a linear algebra course (either before coming to uchicago or in undergrad) that exposure should be more than enough to understand how linear regression works.

**Comment by Otamio** [comment]
This one looks pretty detailed, thanks!
