### ISSUE TITLE
How to commit? 

### ISSUE THREAD

**Issue by DH1460** [UC-MACSS/persp-model_W18#11]
Hi there, 

I am having trouble figuring out how to commit my PS1. I am working on the PS1 in a tex.file in RStudio. Am I doing right? Using compile option in tool section in RStudio, I can get the pdf version of my PS1. Could you let me know how to commit to Github?

**Comment by DH1460** [comment]
To anyone who's wondering the similar issue: 
Download GitHub.mac, it's convenient to commit and push from there!

**Comment by rickecon** [comment]
@DH1460 . I'm glad you have found a GitHub client that you like. I prefer using the command line, but you are welcome to use GitHub.mac. The [GitHub tutorial](https://github.com/UC-MACSS/persp-model_W18/blob/master/tutorials/git_tutorial.pdf) specifies the steps to submitting a pull request. 
1. Set up a GitHub account.
2. Fork the course repository
3. Clone your fork of the the repository (not the main repository) to your local machine.
4. Set the main repository as the "upstream" remote.
5. Make changes to your local repository (e.g., create your problem set document).
6. Commit and push those changes to your remote forked repository (remote=origin, not remote=upstream).
7. Then go online to your branch of the remote fork of the repository and submit a pull request (PR).
8. I can still make commits to that branch, and those commits will automatically update in the PR.
