### ISSUE TITLE
Question on assignment 1 problem 2(f)

### ISSUE THREAD

**Issue by yuqian919** [UC-MACSS/persp-model_W18#2]
Hi Professor Evans and TAs:

In problem 2(f), we need to come up with a preliminary test to test whether our factors are significant or not. I am wondering if it means we need to design an experiment to collect data and validate our hypothesis? Thank you so much!

**Comment by rickecon** [comment]
@yuqian919. No, you don't have to perform a test. You just need to describe how you would perform a test of whether those factors are significant.
