### ISSUE TITLE
Can't make separate PS5 pull request

### ISSUE THREAD

**Issue by lpwarner** [UC-MACSS/persp-model_W18#227]
I believe this is because I am not using a separate PS5 branch (I had problems using branch with PS4) but:

When I made my PS5 commit and push, it automatically joined an old pull request. So I haven't been able to make a separate pull request.

Please do let me know if this is OK, or if you would prefer me to try again using a separate branch?

**Comment by sushmitavgopalan16** [comment]
This is fine
