### ISSUE TITLE
Submission Issue: Authentication failed

### ISSUE THREAD

**Issue by yilundai** [UC-MACSS/persp-model_W18#4]
<img width="604" alt="screen shot 2018-01-07 at 2 20 17 pm" src="https://user-images.githubusercontent.com/32254395/34653749-1813a4e2-f3b6-11e7-9941-10edcecfd58b.png">
When I tried to push my commits through GitHub desktop, it gives me the error message: "Authentication failed. You may not have access to the repository." How should I resolve this issue?

Thanks!

**Comment by cernhofer** [comment]
Have you forked the repository? Normally students will get authentication errors when trying to push to the master repo instead of their own forked repo.
